### PR TITLE
Fix #33

### LINKED ISSUE #33: [1.12.2] Crash with Future MC [java.lang.NoSuchMethodError]
Hello, 

As stated in issue #32. FutureMC causes MIA to crash.

Setting all FutureMC-related options in **ALL** configs to MIA especially the "`future_mc.cfg`" to false doesn't fix the issue, unlike the above issue. Even just setting all options in "`future_mc.cfg`" to false and regenerating all new configs does nothing to fix the issue on my end. There has to be some other conflict somewhere.

Removing MIA or FutureMC from this pack and Minecraft loads perfectly fine. Both mods alone with the above changes work fine but there has to be some conflict somewhere.

[crash-2022-04-23_05.36.43-client.txt](https://github.com/SokyranTheDragon/Minor-Integrations-and-Additions-MIA-/files/8546636/crash-2022-04-23_05.36.43-client.txt)

### PR DESCRIPTION
**Pull request by kappa-maintainer**

### CODE REVIEW

**Review by Codetoil — COMMENTED** [review]
Changes:
- FutureMC: 0.2.7.4→0.2.9
- Integration Foregoing is now properly included in Gradle.
- Upgrade to Gradle 4.9.
- Now uses `net.minecraft.item.crafting.Ingredient` instead of `net.minecraft.item.ItemStack` in the FutureMC Integration. Should fix #33.

**Comment by Codetoil** [comment]
@SokyranTheDragon

**Comment by SokyranTheDragon** [comment]
Sorry it's taking so long, been really busy and having issues IRL.

**Comment by kappa-maintainer** [comment]
At least in my game, the jer entries may be registered after loading complete, these nulls caused exceptions

**Pull request merged**
